* My Emacs Configuration

This is my emacs configuration repository.

** Dependences
   - cmake
   - git
   - libvterm
     It's used for the vterm.
     If you are an Arch user, you can install it by:
     #+begin_src shell
       sudo pacman -S libvterm
     #+end_src
   - The dependences in [[https://github.com/manateelazycat/emacs-application-framework][Emacs Application Framework]].(To use EAF)
   - The dependences in [[https://github.com/loyalpartner/english-teacher.el][english-teacher.el]].(To use english-teacher)

** Installation
   To use my configuration, you should run ~make install~ to download the EAF.And then you can open emacs.

** Functions
   My package manager is ~package-require~ (A package manager written by me), and it's like ~use-package~.
   You can read its code in [[https://github.com/SpringHan/.emacs.d/blob/master/etc/init-require-package.el][init-require-package.el]].

** Transparent Background
   The transparent background is off by default.You can use ~C-z C-a~ to change it.Or if you want it to open by default, you can delete the ~not-alpha~ file.

** Last
   I'm new in emacs, I'll continue to update my configuration everyday.

   You can also see my [[https://github.com/SpringHan/nvim][NeoVim Configuration]].
